// Real-browser smoke checks using Chromium's DevTools protocol; no npm dependencies.
// Set CHROME_PATH if Chromium is installed elsewhere.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const {spawn}=require('node:child_process');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const browserPath=process.env.CHROME_PATH||path.join(process.env.LOCALAPPDATA,'ms-playwright/chromium-1243/chrome-win64/chrome.exe');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const server=require('../server.cjs').createApp({secure:false});
let browser,ws;
(async()=>{
  const testHost=process.env.ROAM_TEST_HOST||'127.0.0.1';
  await new Promise(r=>server.listen(0,testHost==='127.0.0.1'?'127.0.0.1':'0.0.0.0',r));
  const origin=`http://${testHost}:${server.address().port}`;
  const profile=fs.mkdtempSync(path.join(os.tmpdir(),'roam-browser-test-'));
  browser=spawn(browserPath,['--headless','--disable-gpu','--no-first-run','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true});
  const debugURL=await new Promise((resolve,reject)=>{
    let output='';const timer=setTimeout(()=>reject(new Error('Browser startup timed out')),20000);
    browser.on('error',reject);browser.stderr.on('data',data=>{output+=data;const match=output.match(/DevTools listening on (ws:\/\/\S+)/);if(match){clearTimeout(timer);resolve(match[1])}});
  });
  ws=new WebSocket(debugURL);await new Promise(r=>ws.onopen=r);
  let serial=0,session;const pending=new Map(),errors=[];
  ws.onmessage=({data})=>{const msg=JSON.parse(data);if(msg.id){const item=pending.get(msg.id);pending.delete(msg.id);if(msg.error)item.reject(new Error(msg.error.message));else item.resolve(msg.result)}if(msg.method==='Runtime.exceptionThrown')errors.push(msg.params.exceptionDetails.text+' '+JSON.stringify(msg.params.exceptionDetails.exception))};
  function cdp(method,params={},useSession=true){return new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params,...(useSession&&session?{sessionId:session}:{})}))})}
  async function evaluate(expression){const result=await cdp('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(JSON.stringify(result.exceptionDetails));return result.result.value}
  async function until(expression){for(let i=0;i<100;i++){if(await evaluate(expression))return;await delay(100)}throw new Error('Timed out: '+expression)}
  const {targetId}=await cdp('Target.createTarget',{url:'about:blank'},false);
  ({sessionId:session}=await cdp('Target.attachToTarget',{targetId,flatten:true},false));
  await cdp('Runtime.enable');await cdp('Page.enable');
  await cdp('Emulation.setDeviceMetricsOverride',{width:1365,height:1000,deviceScaleFactor:1,mobile:false});
  await cdp('Page.navigate',{url:origin+'/index.html'});
  await until('!!document.querySelector("#login-form")');
  await evaluate('document.querySelector("#username").value="user123";document.querySelector("#password").value="wrong";document.querySelector("#login-form").requestSubmit()');
  await until('document.querySelector("#login-error").textContent.includes("Incorrect")');
  await evaluate('document.querySelector("#password").value="password";document.querySelector("#login-form").requestSubmit()');
  await until('!!document.querySelector("#sign-out")');
  if(testHost!=='127.0.0.1')assert.equal(await evaluate('window.isSecureContext'),false,'Exercise the ordinary HTTP phone context');
  await evaluate('location.hash="#feed"');
  await until('!!document.querySelector(".view-itinerary")');
  await evaluate(`document.querySelector('.cover-link[href="#trip/kyoto"]').click()`);
  await until('document.querySelector("#app").textContent.includes("Day 5")');
  assert.equal(await evaluate('document.querySelectorAll("[data-stop]").length'),0,'Friend itinerary is read-only');
  await evaluate('document.querySelector("[data-trip-tab=photos]").click()');
  await until('document.querySelector("#app").textContent.includes("Illustrative destination photo")');
  assert.equal(await evaluate('!!document.querySelector("[data-photo-upload]")'),false);
  await evaluate('document.querySelector("[data-copy=kyoto]").click()');
  await until('!!document.querySelector("[data-stop]")');
  assert.equal(await evaluate('state.trips.find(t=>t.id==="kyoto").stops[0].done'),false);
  await evaluate('location.hash="#trip/hangzhou-shanghai-2026"');
  await until('!!document.querySelector("[data-trip-tab=expenses]")');
  await evaluate('document.querySelector("[data-trip-tab=photos]").click()');
  await until('document.querySelector("#photo-gallery").textContent.includes("Your first memory")');
  await evaluate(`(async()=>{const c=document.createElement('canvas');c.width=30;c.height=30;c.getContext('2d').fillRect(0,0,30,30);const blob=await new Promise(r=>c.toBlob(r,'image/png'));const dt=new DataTransfer();dt.items.add(new File([blob],'test-memory.png',{type:'image/png'}));const input=document.querySelector('[data-photo-upload]');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await until('document.querySelector("#photo-feedback").textContent.includes("1 photo saved")');
  assert.equal(await evaluate('document.querySelectorAll("#photo-gallery img").length'),1);
  await evaluate(`const form=document.querySelector('[data-photo-caption]');form.elements.caption.value='West Lake memory';form.requestSubmit()`);
  await until('document.querySelector("#photo-gallery img").alt==="West Lake memory"');
  await cdp('Page.reload');
  await until('!!document.querySelector("[data-trip-tab=photos]")');
  await evaluate('document.querySelector("[data-trip-tab=photos]").click()');
  await until('document.querySelector("#photo-gallery img")?.alt==="West Lake memory"');
  // Export and restore includes photo blobs and does not overwrite existing trips.
  await evaluate('(async()=>{globalThis.testBackup=await buildBackup()})()');
  assert.equal(await evaluate('testBackup.photos.length'),1);
  const before=await evaluate('state.trips.length');
  await evaluate('(async()=>{globalThis.restoreResult=await restoreBackup(testBackup)})()');
  assert.equal(await evaluate('state.trips.length'),before+await evaluate('testBackup.trips.length'));
  assert.equal(await evaluate('(async()=>(await photoTransaction("readonly",s=>s.getAll())).length)()'),2);
  assert.equal(await evaluate('(()=>{try{validateBackup({format:"roam-travel-backup",version:1,trips:[{own:true,id:"<script>"}],visited:[],photos:[]});return false}catch{return true}})()'),true);
  await evaluate('document.querySelector("[data-trip-tab=itinerary]").click()');
  await evaluate(`document.querySelector('[data-day="4"]').click()`);
  assert.equal(await evaluate('document.querySelectorAll(".itinerary-day").length'),1);
  await evaluate('document.querySelector("[data-edit-stop]").click()');
  await evaluate('document.querySelector("#edit-stop [name=name]").value="Updated breakfast plan";document.querySelector("#edit-stop [name=notes]").value="Meet in the lobby";document.querySelector("#edit-stop").requestSubmit()');
  await until('document.querySelector("#app").textContent.includes("Meet in the lobby")');
  await evaluate('document.querySelector("#journal").value="First trip journal entry";document.querySelector("#trip-journal").requestSubmit()');
  await evaluate('document.querySelector("[data-trip-tab=expenses]").click()');
  await evaluate('document.querySelector("#add-expense [name=amount]").value="52";document.querySelector("#add-expense [name=name]").value="Test dinner";document.querySelector("#add-expense").requestSubmit()');
  assert.equal(await evaluate('state.trips.find(t=>t.id==="hangzhou-shanghai-2026").expenses.at(-1).sgd'),10);
  await cdp('Page.reload');
  await until('!!document.querySelector("[data-trip-tab=photos]")');
  assert.equal(await evaluate('state.trips.find(t=>t.id==="hangzhou-shanghai-2026").journal'),'First trip journal entry');
  await evaluate('document.querySelector("[data-trip-tab=photos]").click()');
  await until('document.querySelector("#photo-gallery img")?.alt==="West Lake memory"');
  // Unsupported files produce a useful error and do not create a gallery item.
  await evaluate(`const dt=new DataTransfer();dt.items.add(new File(['bad'],'not-a-photo.txt',{type:'text/plain'}));const input=document.querySelector('[data-photo-upload]');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));`);
  await until('document.querySelector("#photo-feedback").textContent.includes("Choose JPEG")');
  assert.equal(await evaluate('document.querySelectorAll("#photo-gallery img").length'),1);
  await evaluate('document.querySelector("[data-photo-delete]").click()');
  await until('document.querySelector("#photo-gallery").textContent.includes("Your first memory")');
  await evaluate('location.hash="#trip/kyoto"');
  await until('document.querySelector("#app").textContent.includes("Day 5")');
  fs.mkdirSync(path.join(root,'docs/previews'),{recursive:true});
  let shot=await cdp('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(root,'docs/previews/friend-itinerary-desktop.png'),Buffer.from(shot.data,'base64'));
  await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  assert(await evaluate('document.documentElement.scrollWidth <= innerWidth'),'Mobile horizontal overflow');
  await evaluate('location.hash="#trip/hangzhou-shanghai-2026"');await until('!!document.querySelector("[data-trip-tab=expenses]")');
  await evaluate('document.querySelector("[data-trip-tab=photos]").click()');await until('!!document.querySelector("[data-photo-upload]")');
  assert(await evaluate('document.documentElement.scrollWidth <= innerWidth'),'Mobile photo overflow');
  shot=await cdp('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(root,'docs/previews/trip-photos-mobile.png'),Buffer.from(shot.data,'base64'));
  await evaluate('document.querySelector("#sign-out").click()');
  await until('!!document.querySelector("#login-form")');
  assert.equal(await evaluate('(async()=>(await fetch("/prototype-trip.js")).status)()'),401);
  await cdp('Page.navigate',{url:origin+'/index.html'});
  await until('!!document.querySelector("#login-form")');
  shot=await cdp('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(root,'docs/previews/prototype-login-mobile.png'),Buffer.from(shot.data,'base64'));
  assert.deepEqual(errors,[]);
  console.log('PASS: real login, wrong password, session reload, logout and asset protection; friend/photo/backup/journal/spending regression checks; desktop/mobile layouts');
  await cdp('Browser.close',{},false);
})().catch(error=>{console.error(error);process.exitCode=1}).finally(()=>{ws?.close();browser?.kill();browser?.stdout?.destroy();browser?.stderr?.destroy();browser?.unref();server.closeAllConnections();server.close()});
