"""Regenerate the planning HTML and screen catalogue; no application code."""
from pathlib import Path
import html
import json
import re

ROOT = Path(__file__).resolve().parents[1]

# Each screen specifies a distinct layout, content, navigation, and failure state.
SCREENS = [
('welcome', 'Welcome', '/', 'P1', 'Start your travel collection', 'Keep the plan. Keep the memories. See the world through your friends.', 'hero:Your world, in colour|stats:Countries • Cities • Memories|card:Plan before you go, or add a trip you already took.|card:Follow friends and make their routes your own.', 'Create account>signup|Explore public trips>explore', 'Signed-out browsing; private links request sign-in without exposing trip details.'),
('signup', 'Create account', '/signup', 'P1', 'A world of memories starts here', 'Use one account on the website and your phone.', 'field:Name|field:Email|field:Password|check:Accept terms and privacy policy|card:Already registered? Sign in below.', 'Create account>verify|Sign in>login', 'Invalid email, weak password, account exists, submitting, and connection failure.'),
('verify', 'Verify email', '/verify', 'P1', 'Check your inbox', 'Confirm your email to finish creating your account.', 'card:Verification email sent to a•••@example.com|card:Open the link on this device, or continue after verification.|field:Correct email address', 'Continue>onboarding|Resend email>verify|Change email>signup', 'Expired link, resend cooldown, callback failure, and verified state.'),
('login', 'Sign in', '/login', 'P1', 'Welcome back', 'Your trips are waiting.', 'field:Email|field:Password|check:Keep me signed in on this device', 'Sign in>home|Forgot password>recovery|Create account>signup', 'Invalid credentials, offline, expired session, and redirected private-link destination.'),
('recovery', 'Account recovery', '/recovery', 'P1', 'Get back to your travels', 'Request a reset link, then choose a new password.', 'field:Email|card:We will send instructions if an account matches.|field:New password (after opening the reset link)', 'Send reset link>recovery|Save password>login', 'Generic response prevents email enumeration; expired token and retry states.'),
('onboarding', 'Set up profile', '/onboarding', 'P1', 'Make the map yours', 'You can add old trips before finding friends.', 'field:Handle|field:Display name and bio|photo:Choose profile photo|check:Private profile|card:Add visited countries now or skip and return later.', 'Colour my map>mapedit|Find people>people|Skip>home', 'Handle collision; avatar upload failure; all optional steps can be skipped.'),
('home', 'Following feed', '/home', 'P2', 'Your people, out in the world', 'Following is the default. Explore is always one tap away.', 'chips:Following • Friends|status:Alex is in Spain now · manually shared · ends 18 Sep|photo:Alex · 5 days in Barcelona|card:Alex added 12 memories · Followers · 24 likes · 6 comments|card:Maya completed a Japan trip · Save the route for later', 'Open Alex’s trip>trip|View Alex>friend|See notifications>notifications', 'No follows: import your own trip and find people. Also loading, pagination, unavailable post, and retry.'),
('explore', 'Explore and search', '/explore', 'P3', 'Where will you go next?', 'Places, routes, and useful answers from travellers.', 'field:Search destinations, people, places, guides|chips:Friends’ trips • Destinations • Practical guides • People|photo:Japan · routes saved by people you follow|card:Barcelona in five days · city walks and food|card:Later: clearly labelled creator collections', 'Japan>destination|People>people|Practical guides>guides|Creators>creators', 'No results, spelling suggestions, popular public content, filtered/blocked results, and retry.'),
('people', 'Find people', '/people', 'P2', 'Travel is better with context', 'Find friends by name or handle.', 'field:Search people|card:Alex · @alextravels · 12 countries · Following|card:Maya · @maya · 8 countries · Follow|card:Sam · Private profile · Request to follow', 'View Alex>friend|Follow requests>followers', 'No automatic contact upload; empty results, pending request, accepted follow, and blocked account.'),
('trips', 'My trips', '/trips', 'P1', 'Your travel shelf', 'Plans and memories, together.', 'chips:All • Planned • Ongoing • Completed • Archived|photo:Japan · 12–20 Oct · Planned · Private|photo:Barcelona · 5 days · Completed · Followers|card:Add a past trip even if you do not remember the exact dates.', 'Open trip>trip|Add a trip>add|Saved trips>saved', 'Empty shelf, date-unknown trip, sync pending, search/filter empty, and archived trips.'),
('add', 'Add chooser', '/add', 'P1', 'How do you want to begin?', 'Every option creates the same flexible trip journal.', 'card:Plan a future trip · organise your days before departure|card:Record a past trip · add stops, notes, and memories|card:Start from photos · reconstruct the journey with your review', 'Plan a trip>tripnew|Record past trip>tripnew|Import photos>upload', 'Choose existing trip for imports; cancelling leaves no accidental published draft.'),
('tripnew', 'Create / edit trip', '/trips/new', 'P1', 'Give your trip a home', 'Future plans and past memories get equal support.', 'field:Trip title · Barcelona with friends|field:Destinations · Spain|field:Start and end dates · or month/year/unknown|chips:Future plan • Past trip|field:Visibility · Private / Followers / Public|photo:Choose cover', 'Save draft>trip|Add itinerary>itinerary|Add photos>upload', 'Invalid dates, unknown historical dates, saving, stale edit, and unsaved-changes prompt.'),
('trip', 'Trip overview', '/trips/:id', 'P1', 'Barcelona with friends', '5 days · Spain · Completed · Followers', 'photo:Trip cover · caption and accessible description|chips:Overview • Itinerary • Photos • Map|stats:5 days • 14 stops • 36 photos|card:Alex · A slow week of food, architecture, and beach walks.|card:Day 1 · Gothic Quarter → waterfront', 'Itinerary>itinerary|Photos>photos|Trip map>tripmap|Like / comment>comments|Save a copy>copy|Share>share|Edit>tripnew', 'Owner sees editing; visitor sees follow/save. Private, deleted, draft, and partially uploaded states.'),
('itinerary', 'Daily itinerary editor', '/trips/:id/itinerary', 'P1', 'The plan and what happened', 'Keep the original plan while recording your actual route.', 'chips:Day 1 • Day 2 • Day 3 • + Day|chips:Planned • Actual|timeline:09:00 · Gothic Quarter · Visited|timeline:12:30 · Lunch · Planned|timeline:16:00 · Waterfront · Visited · 6 photos|field:Day notes', 'Add / edit stop>stop|Import suggestions>reconstruct|View route>tripmap|Trip overview>trip', 'Reorder via drag or buttons, time conflicts, unknown dates, skipped stops, offline draft, and edit conflict.'),
('stop', 'Stop editor', '/trips/:id/stops/:stopId', 'P1', 'Add a stop to your day', 'A place can be planned, visited, or skipped.', 'field:Place search or manual place|field:Day and local time (optional)|chips:Planned • Visited • Skipped|field:Public itinerary note|field:Private note · only you|photo:Attach your photos', 'Save stop>itinerary|View place>place', 'Place not found, timezone ambiguity, duplicate warning, private note label, and delete confirmation.'),
('tripmap', 'Trip route map', '/trips/:id/map', 'P1', 'See the route', 'Display planned and actual stops separately.', 'map:Barcelona · route with numbered stops|chips:Planned route • Actual visits|timeline:1 · Gothic Quarter|timeline:2 · Waterfront|card:Routes illustrate stop order, not turn-by-turn navigation.', 'Open stop>stop|Back to itinerary>itinerary', 'Map unavailable uses ordered list; hidden stops excluded; route gaps and unknown locations labelled.'),
('upload', 'Photo upload', '/trips/:id/upload', 'P1', 'Bring your memories together', 'Select photos or drop a batch on the website.', 'photo:Choose photos · JPG / PNG / supported HEIC conversion|card:12 selected · 8 uploaded · 2 processing · 2 queued|check:Use photo timestamps and location metadata to suggest stops|check:Optional: send selected photos for AI location suggestions|card:You will review suggestions before they change your trip.', 'Review suggestions>reconstruct|View album>photos', 'Per-file retry, cancel, quota limit, denied photo access, duplicates, corrupt files, and offline queue.'),
('reconstruct', 'Reconstruction review', '/trips/:id/reconstruction', 'P3', 'Does this match your trip?', 'Suggestions become trip records only after you approve them.', 'chips:All • Needs review • Confirmed|photo:Photo 08 · possible Sagrada Família|card:Evidence: scene suggestion · location unconfirmed|timeline:Day 2 · 10:14 photo timestamp · timezone unknown|field:Choose another place or leave unresolved|card:Photo 09 · GPS-derived candidate · review location', 'Confirm selected>itinerary|Change place>stop|Skip unresolved>photos', 'Queued, processing, partial results, failure/retry, cancel, conflicting manual edits, and no useful candidates.'),
('photos', 'Trip photo gallery', '/trips/:id/photos', 'P1', 'The memories', 'Grouped by day, with captions and places.', 'chips:All photos • Day 1 • Day 2 • Unsorted|photo:Day 1 · City walk · 12 photos|photo:Day 2 · Architecture · 18 photos|photo:Unsorted · 6 photos', 'Open photo>photo|Add photos>upload|Trip overview>trip', 'Empty gallery, processing placeholders, hidden private media, failed thumbnail, and selection mode.'),
('photo', 'Photo viewer / edit', '/photos/:id', 'P1', 'A moment worth keeping', 'Owner controls appear beside the memory.', 'photo:Large photo placeholder · 8 of 36|field:Caption · Morning light in Barcelona|field:Date/time · editable, original retained privately|field:Place · confirmed by you|card:Visible to followers through this trip.', 'Save edits>photos|Open place>place|Report>report', 'Owner edit versus visitor view; delete confirmation; missing original; metadata privacy and alt text.'),
('comments', 'Trip reactions and discussion', '/trips/:id/comments', 'P2', 'Talk about the trip', 'Ask for the details a photo does not explain.', 'card:24 likes · View people who liked|card:Maya: Did you book the train ahead?|card:Alex: Yes — added a note to Day 2.|field:Write a comment', 'Post comment>comments|Back to trip>trip|Report comment>report', 'Posting/retry, edit/delete own comment, removed comment, and source no longer visible.'),
('copy', 'Save itinerary copy', '/trips/:id/copy', 'P2', 'Make this route your own', 'Your copy stays independent of the original.', 'field:New trip title|field:New start date (optional)|check:Include permitted itinerary notes|card:Credit: inspired by Alex’s Barcelona trip. Source photos and private notes are not copied.|field:Your copy starts Private', 'Create my copy>itinerary|Cancel>trip', 'Source private/deleted, copying disabled if supported, duplicate request protection, and date-shift preview.'),
('share', 'Share trip / showcase', '/share/:type/:id', 'P2', 'Choose what people can see', 'Preview the audience before sharing a link or card.', 'field:Audience · Private / Followers / Public|photo:Share preview with permitted cover and stats|field:Share link|card:People still need access to open a followers-only trip. Downloaded public cards cannot be recalled.', 'Apply audience>trip|Profile showcase>profile', 'Unavailable source, audience change confirmation, copied-link feedback, and image generation failure.'),
('profile', 'My profile showcase', '/me', 'P1', 'Your world, in colour', 'Jamie · @jamie · Collect places. Keep the stories.', 'world:Your visited-country collection|stats:20 countries • 43 sample cities • 12 sample trips|chips:Showcase • Trips • Saved • Badges|card:Colour a country when you visit. Add a note or connect a trip.|photo:Featured trip · Barcelona with friends', 'Edit travel map>mapedit|Full world map>world|Edit profile>profileedit|Country status>presence|Badges>badges|Settings>settings', 'New profile starts with an inviting empty world map; owner-only versus public preview counts clearly separated.'),
('friend', 'Other traveller profile', '/u/:handle', 'P2', 'Alex’s travel showcase', '@alextravels · Following · Alex is in Spain now', 'world:Explore Alex’s visible travels|stats:20 visible countries • 43 sample cities • 12 sample trips|chips:Showcase • Trips • Followers|card:Travel notes and totals reflect what Alex chose to share.|photo:Barcelona with friends · View itinerary', 'Open trip>trip|Country detail>country|Followers>followers|Report / block>report', 'Private profile/request pending; blocked; user not found; hidden visits excluded from map and counts.'),
('profileedit', 'Edit profile', '/me/edit', 'P1', 'Make it feel like you', 'Your travel identity, with clear visibility choices.', 'photo:Avatar|field:Name / handle / bio|field:Profile visibility|field:Showcase accent colour|check:Show shared country and city totals|check:Show badges', 'Save profile>profile|Edit countries>mapedit', 'Handle taken, image upload failure, privacy transition preview, and unsaved changes.'),
('world', 'Flat world map', '/me/map', 'P1', 'Fill your world with colour', 'Tick countries on the map or use the searchable country list.', 'world:Visited countries showcase|chips:World map • Flat map • Country list|stats:20 countries • 43 sample cities|field:Search country or city|chips:Visited • Wishlist • All years|card:Legend: teal = visited · outline = wishlist · grey = unvisited', 'Edit visits>mapedit|Country details>country|Back to profile>profile', 'Map rendering failure, reduced motion, keyboard/list mode, no visits, small-country picking, and audience preview.'),
('mapedit', 'Mark countries / annotations', '/me/map/edit', 'P1', 'Colour in your travels', 'Manual backfill counts. Photos are optional.', 'world:Select a country to mark visited|field:Country · Spain|check:Visited this country|field:Cities · Barcelona, Madrid|field:When · exact date / month / year / unknown|field:Travel note · What made this place memorable?|field:Linked trip (optional)|field:Showcase audience · Private / Followers / Public', 'Save visit>world|Country details>country', 'Repeated visits, canonical city duplicates, remove-last-visit confirmation, wishlist separation, and private-trip warning.'),
('country', 'Country travel drawer', '/countries/:code/showcase', 'P1', 'Spain · the stories behind the colour', 'Showcase annotations and linked memories.', 'map:Spain · Barcelona / Madrid|stats:2 cities • 2 visible trips|card:First visit: 2024 · self-reported|card:Travel note: return for a slower train journey.|photo:Barcelona with friends', 'Open linked trip>trip|Explore destination>destination|Edit my visit>mapedit', 'Owner edit only; no shared notes; private linked trip omitted; repeated visits grouped.'),
('presence', 'Country status editor', '/me/status', 'P2', 'Let people know you are there', 'Manual country sharing. You control when it ends.', 'check:Share country status · On|field:Country · Spain|field:Audience · Followers / Everyone|field:Ends · 18 September, 23:59|status:Preview: Jamie is in Spain now|card:Everyone makes this public. No live GPS tracking.', 'Save status>profile|Turn off>profile', 'Missing expiry, past expiry, timezone display, offline save failure, and public audience confirmation.'),
('followers', 'Followers / requests', '/me/connections', 'P2', 'Your travel circle', 'Manage follows and requests in one place.', 'chips:Followers • Following • Requests|card:Maya · Follow back|card:Sam · Follow request · Accept / Decline|card:Alex · Following · Remove follower', 'View traveller>friend|Find people>people', 'Empty requests, removed follower loses follower access, blocked accounts filtered, and pagination.'),
('saved', 'Saved trips and collections', '/me/saved', 'P2', 'Ideas for the next adventure', 'Bookmarks stay linked; copied plans belong to you.', 'chips:Trips • Places • Guides • Collections|photo:Japan route · Saved from Maya|card:European rail basics · Guide bookmark|card:Spain food stops · Place collection', 'Open saved trip>trip|Copy itinerary>copy|Read guide>guide', 'Source made private/deleted; explain unavailable bookmark without exposing content; empty collection.'),
('destination', 'Destination hub', '/destinations/:slug', 'P3', 'Japan, through travellers’ eyes', 'Friends’ experiences first, with practical context.', 'photo:Destination cover|stats:Visible trips • Traveller reviews • Practical guides|chips:Friends • All travellers • Budget • Family|card:Maya’s 9-day route · 3 cities|card:Before you go: transport and payment setup', 'View trip>trip|Places>place|Practical guides>guides|Questions>forum', 'No friend content uses labelled public results; empty reviews; stale editorial information labelled.'),
('place', 'Place details and reviews', '/places/:id', 'P3', 'A place with traveller context', 'Know who visited, when, and what helped.', 'map:Place location|chips:Overview • Reviews • Photos|card:Traveller review · visited May 2026 · solo trip · linked stop|card:Practical tip: allow time to explore the surrounding streets.|photo:Traveller photos · attributed to their authors', 'Write review>review|Save to itinerary>stop|View reviewer>friend', 'No reviews; self-reported visit label; closed/duplicate place report; external sources visibly separate.'),
('review', 'Write / edit review', '/places/:id/review', 'P3', 'What would help another traveller?', 'Add context rather than only a star rating.', 'field:Rating|field:Visit month/year|field:Link your visited trip stop (optional)|chips:Solo • Couple • Family • Friends • Budget|field:What worked? What should someone know?|photo:Add your own photos', 'Publish review>place', 'Invalid/missing fields, draft recovery, source trip made private, spam review, and save failure.'),
('guides', 'Practical guide library', '/guides', 'P3', 'Before you depart', 'Useful answers for the days before your trip.', 'field:Search country or topic|chips:Payments • Trains • Driving • Connectivity|card:China · Getting started with payment apps|card:Europe · Rail tickets and validation|card:Germany · Driving preparation', 'Read guide>guide|Ask the community>forum', 'No guide yet, outdated label, editorial filters, and saved-only empty state.'),
('guide', 'Practical guide article', '/guides/:slug', 'P3', 'Rail travel: preparation checklist', 'Illustrative article layout, not travel advice.', 'card:Country / region · Editorial author · Last checked date|timeline:1 · Before departure|timeline:2 · At the station|timeline:3 · If your plans change|card:Official source links and corrections history|card:Was this useful? Helpful / Suggest a correction', 'Save guide>saved|Discuss / ask>thread|Report correction>report', 'Sources unavailable, review overdue, region applicability notice, and version history.'),
('forum', 'Practical forum', '/community', 'P3', 'Ask people who have been', 'Destination-specific questions with helpful answers.', 'field:Search questions|chips:Destination • Unanswered • Helpful • Recent|card:How do I know whether my ticket needs validation? · 4 answers|card:Payment setup before arrival · 7 answers', 'Open question>thread|Ask a question>question', 'Empty topic, duplicate suggestions, moderation pending, locked topic, and rate limit.'),
('thread', 'Question and answers', '/community/questions/:id', 'P3', 'A practical travel question', 'Destination · Asked by Maya · Updated recently', 'card:Question text with dates and travel context|card:Accepted answer · source links where relevant|card:Other answer · 12 helpful votes|field:Write an answer', 'Submit answer>thread|Report>report|Back to forum>forum', 'Deleted answer, moderation pending, locked thread, edited acceptance, and signed-out reply prompt.'),
('question', 'Ask / edit question', '/community/new', 'P3', 'Give people enough context', 'Specific questions are easier to answer.', 'field:Question title|field:Destination / topic|field:Travel dates or period (optional)|field:What have you checked? What is unclear?|card:Similar questions will appear before publishing.', 'Publish question>thread', 'Duplicate suggestion, required fields, draft save, spam limit, and moderation review.'),
('badges', 'Badges and progress', '/me/badges', 'P3', 'Your growing travel collection', 'Celebrate memories at your own pace.', 'world:Your coloured-country collection|stats:20 countries • 43 sample cities • 3 badges|card:First memory · earned|card:Five countries · earned|card:Next milestone · ten cities with a saved note|check:Show achievements on profile', 'Friend leaderboard>leaderboard|Add a visit>mapedit', 'Opt-out, recalculated badges after deletion, no daily-travel pressure, and no private-location disclosure.'),
('leaderboard', 'Friend leaderboard', '/leaderboard', 'P3', 'A little friendly inspiration', 'Optional rankings. Visits are self-reported.', 'chips:Countries • Cities • Logged trips|card:1 · Maya · 9 shared countries|card:2 · Jamie · 6 shared countries|card:3 · Alex · 6 shared countries|check:Join leaderboard', 'View profile>friend|My badges>badges', 'Opt-in required, ties, blocked accounts excluded, and only explicitly shared counts used.'),
('notifications', 'Activity inbox', '/notifications', 'P2', 'Travel updates', 'Choose what deserves your attention.', 'chips:All • Follows • Reactions • Trips|card:Maya requested to follow you.|card:Alex commented on your trip.|card:Your photo import is ready for review.', 'Follow requests>followers|Open comment>comments|Review import>reconstruct|Preferences>settings', 'Read/unread, no activity, stale source access, pagination, and no private lock-screen details.'),
('settings', 'Settings', '/settings', 'P1', 'Your account, your choices', 'Privacy and data controls should be easy to find.', 'card:Profile and trip privacy defaults|card:Notifications · in-app / push / email|card:Photo metadata and AI consent|card:Blocked accounts|card:Language, appearance, accessibility|card:Export and delete account', 'Privacy controls>privacy|Data export / deletion>data|Edit profile>profileedit|Help>help', 'Save failure, reauthentication, denied OS push permissions, and account session expiry.'),
('privacy', 'Privacy and blocked accounts', '/settings/privacy', 'P1', 'Choose your audience', 'Shared map totals follow the same visibility as shared visits.', 'field:Default trip audience|field:Default country-status audience|check:Private profile|check:Allow profile discovery|card:Blocked people · unblock action|card:Preview your profile as a visitor', 'Save settings>settings|Visitor preview>friend', 'Explain existing content changes; confirm narrowing/widening audience; public data remains public when anonymous.'),
('data', 'Export / delete account', '/settings/data', 'P1', 'Your memories belong to you', 'Request a copy or remove your account.', 'card:Export trips, notes, visits, and your photos · status: not requested|card:Exports expire and are available only to your account.|field:Confirm account identity before deletion|card:Deletion removes your media and profile; show retention details before confirmation.', 'Request export>data|Review deletion>data|Back to settings>settings', 'Queued/running/ready/expired export; reauthentication; deletion confirmation and tracked completion.'),
('report', 'Report or block', '/report', 'P2', 'Tell us what is wrong', 'Reports are private. Blocking changes your interactions.', 'field:Reason · Spam / Harassment / Privacy / Other|field:Additional context|check:Also block this account|card:You will receive a report acknowledgement.', 'Submit report>help|Cancel>home', 'Rate limit, invalid target, already removed content, and private report receipt.'),
('help', 'Help and support', '/help', 'P1', 'Help with your travels here', 'Account, uploads, privacy, and community support.', 'field:Search help|card:Why is my photo still processing?|card:Who can see my map and country status?|card:How do I recover my account?|field:Support request details', 'Send support request>help|Community standards>legal', 'Support receipt, unavailable service, upload diagnostics without private images, and accessibility contact.'),
('legal', 'Policies and community standards', '/policies', 'P1', 'How this community works', 'Policy layout placeholder; actual policies need drafting before launch.', 'chips:Privacy • Terms • Community standards|card:Photo and metadata use|card:Sharing, copying itineraries, and public content|card:Reports, moderation, and appeals|card:Retention, deletion, and contact details', 'Back to help>help', 'Version/date shown; readable signed out; policy text in this prototype is not a final legal document.'),
('admin', 'Moderation dashboard', '/admin', 'P2', 'Keep the community useful', 'Restricted moderator workspace, separate from the public app.', 'stats:Open reports • Pending reviews • Overdue guides|card:Report queue · target / reason / age / assignee|card:Content preview with minimum necessary access|field:Action reason|chips:Dismiss • Hide • Escalate • Suspend', 'Review report>admin|Guide editorial queue>editor', 'Authorisation denied, audit log, appeal/reversal, conflicting moderator actions, and privacy-restricted previews.'),
('editor', 'Guide editorial workspace', '/admin/guides', 'P3', 'Keep practical advice current', 'Draft, review, publish, and check sources.', 'field:Title / slug / destination / topic|field:Article body|field:Official sources|field:Last checked / review due|chips:Draft • In review • Published|card:Corrections and version history', 'Save draft>editor|Preview guide>guide', 'Moderator/editor roles differ; broken sources, stale version conflict, publication validation, and rollback.'),
('creators', 'Creator discovery', '/creators', 'P5', 'Find a travel perspective you like', 'Broader discovery grows after the friends experience works.', 'chips:Cities • Outdoors • Food • Budget|photo:Creator collection · a week of city walks|card:Creator bio · clear sponsorship labels|card:Friends remain in the Following feed.', 'View creator>friend|Open collection>saved', 'No fake verified badge; sponsored versus organic separation; hidden/blocked creators.'),
('groups', 'Traveller groups', '/groups', 'P5', 'Find people with shared plans', 'Choose where and how you want to connect.', 'field:Country / city / interest|chips:Public • Private • My groups|card:Barcelona weekend walks · public|card:Japan autumn travellers · request to join', 'Open group>group|Discover activity>event', 'No groups, membership pending, moderation capacity, and no automatic location inference.'),
('group', 'Group detail', '/groups/:id', 'P5', 'Barcelona weekend walks', 'Group rules and membership come before meeting details.', 'card:About · organiser · rules · member count|chips:Discussion • Activities • Members|card:Saturday city walk · RSVP available|field:Post to group', 'View activity>event|Report group>report', 'Private membership gate, banned member, locked posts, pending join, and organiser permissions.'),
('event', 'Meetup / activity', '/activities/:id', 'P5', 'Saturday city walk', 'An optional way to meet other travellers.', 'field:Date / time / timezone|map:Approximate meeting area|card:Exact meeting details visible to permitted participants|card:Organiser and group rules|chips:Going • Interested • Cancel RSVP', 'RSVP>event|Open group>group|Report activity>report', 'Cancelled/full event, eligibility, private location, changed time notification, and no mandatory GPS.'),
('unavailable', 'Unavailable / offline', '/unavailable', 'P1', 'We cannot open this right now', 'Keep the next step clear without revealing private content.', 'card:This item may be private, removed, or temporarily unavailable.|card:Your unsent draft stays on this device until it can sync.|card:Offline map fallback: searchable visited-country list.', 'Try again>home|My trips>trips|Get help>help', 'Distinct handling for offline, denied, not found, expired link, quota exhausted, and maintenance.')
]

def inline(s):
    s = html.escape(s)
    s = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2">\1</a>', s)
    s = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', s)
    return re.sub(r'`([^`]+)`', r'<code>\1</code>', s)

def markdown(s):
    out, paragraph, table, code = [], [], [], None
    def flush():
        if paragraph:
            out.append('<p>' + inline(' '.join(paragraph)) + '</p>'); paragraph.clear()
        if table:
            rows = [r for r in table if not re.match(r'^\|[\s:|\-]+\|$', r)]
            out.append('<div class="table-scroll"><table>')
            for i,r in enumerate(rows):
                tag = 'th' if i == 0 else 'td'
                out.append('<tr>' + ''.join(f'<{tag}>{inline(c.strip())}</{tag}>' for c in r.strip('|').split('|')) + '</tr>')
            out.append('</table></div>'); table.clear()
    for line in s.splitlines():
        if line.startswith('```'):
            if code is None: flush(); code = []
            else: out.append('<pre><code>' + html.escape('\n'.join(code)) + '</code></pre>'); code = None
            continue
        if code is not None: code.append(line); continue
        if line.startswith('|'):
            if paragraph: flush()
            table.append(line); continue
        if table: flush()
        if not line.strip(): flush(); continue
        m = re.match(r'^(#{1,6}) (.+)', line)
        if m: flush(); n = min(len(m[1])+1,6); out.append(f'<h{n}>{inline(m[2])}</h{n}>'); continue
        if re.match(r'^(\d+\. |\- )', line):
            flush(); out.append('<p class="list-line">' + inline(line) + '</p>'); continue
        paragraph.append(line)
    flush()
    return '\n'.join(out)

catalog = ['# Page and state catalogue', '', 'Planning edition · 8 September 2026.', '',
           'These are the proposed product screens, including launch, operational, and later-phase pages. The HTML renders every screen with illustrative content and clickable navigation. Related modes, dialogs, and errors are listed per screen rather than invented as separate products.', '',
           'Desktop: persistent navigation, central content, contextual right rail. Mobile: one column and five bottom destinations. Profile and world-map screens prominently feature the globe. Screen routes are proposed application routes, not running pages.', '']
for sid,name,route,phase,title,subtitle,blocks,actions,states in SCREENS:
    catalog += [f'## {name}', '', f'**Route:** `{route}` · **Stage:** {phase} · **Wireframe ID:** `{sid}`', '', subtitle, '', '**Layout and content:**', '']
    catalog += ['- ' + b.split(':',1)[1] for b in blocks.split('|')]
    catalog += ['', '**Actions:** ' + '; '.join(a.split('>')[0] for a in actions.split('|')) + '.', '', '**States and rules:** ' + states, '']
(ROOT/'docs/SCREEN_CATALOG.md').write_text('\n'.join(catalog), encoding='utf-8')

overview = markdown((ROOT/'README.md').read_text(encoding='utf-8'))
implementation = markdown((ROOT/'IMPLEMENTATION_PLAN.md').read_text(encoding='utf-8'))
# Relative document links need to resolve from docs/ in the generated HTML.
for old,new in [('href="IMPLEMENTATION_PLAN.md"','href="../IMPLEMENTATION_PLAN.md"'),('href="CHANGELOG.md"','href="../CHANGELOG.md"'),('href="docs/SCREEN_CATALOG.md"','href="SCREEN_CATALOG.md"'),('href="docs/project-blueprint.html"','href="project-blueprint.html"')]:
    overview = overview.replace(old,new)

TEMPLATE = (ROOT/'docs/blueprint-template.html').read_text(encoding='utf-8')
css = (ROOT/'docs/blueprint.css').read_text(encoding='utf-8')
js = (ROOT/'docs/blueprint.js').read_text(encoding='utf-8')
world = json.loads((ROOT/'docs/assets/world-countries.geojson').read_text(encoding='utf-8'))
result = TEMPLATE.replace('__OVERVIEW__', overview).replace('__IMPLEMENTATION__', implementation).replace('__DATA__', json.dumps(SCREENS, ensure_ascii=False)).replace('__WORLD__', json.dumps(world, ensure_ascii=False, separators=(',', ':'))).replace('__CSS__', css).replace('__JS__', js)
(ROOT/'docs/project-blueprint.html').write_text(result, encoding='utf-8')
print(f'Generated {len(SCREENS)} redesigned screens with an embedded flat world map ({len(world["features"])} features).')
